### ISSUE TITLE
BUG: Dropout method in runDArch file

### ISSUE THREAD

**Issue by rz1988** [maddin79/darch#12]
Hi Saviola,

There seems to be a bug in the application of dropout in the runDArch code. In my understanding, the dropout should only be applied to the hidden layers but not the output layer. But in the runDArch code (line 49) the dropout change is applied to the last output layer of a DArch instance. As a result, when dropout is applied, the predictions are worsened. 

## runDArch 

  for(i in 1:length(layers)){
    dropoutWeightChange <- getLayerWeights(darch, i) * darch@dropoutHidden
    data <- cbind(data,rep(1,numRows))
    # temporarily change weights to account for dropout
    setLayerWeights(darch, i) <- getLayerWeights(darch, i) - dropoutWeightChange
    ret <- layers[[i]][[2]](data[],layers[[i]][[1]][])
    setLayerWeights(darch, i) <- getLayerWeights(darch, i) + dropoutWeightChange
    data <- ret[[1]]
    darch <- addExecOutput(darch,data)
  }
  

Thanks,
Ryan

**Comment by rz1988** [comment]
I run darch package from CRAN with version 0.10.0.

**Comment by saviola777** [comment]
Hi Ryan,

thanks for reporting the issue. You are right, this has been fixed in 7d67ed5, now the weights on the last layer are only changed if DropConnect is activated. This will be in the next release, which I hope to publish on CRAN in late April or early May. Until then, I encourage you to try the latest git version, it is currently pretty much stable (but any help in discovering further bugs is greatly appreciated). Many things have changed since version 0.10.0, any many bugs have already been fixed (but I'm sure that many new ones have been introduced, as well).

**Comment by rz1988** [comment]
Thanks for the quick response, Saviola. 

On another note, in 0.10.0 the batches are not randomized. Instead, they are assigned based upon the order they are present in the dataset. I wonder if you have fixed this as well?

Thanks,
Ryan

**Comment by cbohrson** [comment]
I tried upgrading to the latest git release using devtools to avoid the issue described here (thanks Ryan).  It looks like predict.DArch isn't an exported function anymore.  Is this a bug?

Thanks

**Comment by saviola777** [comment]
@rz1988 
Yes, this has been fixed as well, this behavior can now be controlled with the parameter `shuffleTrainData`.

@cbohrson 
This is intentional, since it is an S3 generic which is not supposed to be called directly. Simply call `predict()` with your darch instance (which is returned from the call to `darch()`) and the `predict` generic will call predict.DArch behind the scenes.

**Comment by saviola777** [comment]
Closing after a month of inactivity.
