### ISSUE TITLE
pre-training problems

### ISSUE THREAD

**Issue by Struggle-YD** [maddin79/darch#20]
dear team
 when i try to pre-train my deep net, this is a problem as follows 
## 
library(darch)
data(iris)
model <- darch(Species ~ ., iris,rbm.batchSize=10,rbm.numEpochs=10)
##
Warning messages:
1: In `[<-`(`*tmp*`, i, value = <S4 object of class "RBM">) :
  implicit list embedding of S4 objects is deprecated
2: In `[<-`(`*tmp*`, i, value = <S4 object of class "RBM">) :
  implicit list embedding of S4 objects is deprecated

I'd appreciated your instruction!!!

**Comment by saviola777** [comment]
Hello,

thanks for your feedback. The messages are warnings, not errors, and the training itself should still work as expected. We will try to fix the warnings for the next version, but I can't make any promises as to when that will happen, since the project has not been worked on for the last couple of months.

Please give more details if there are problems beyond these warnings and I'll try to help you solve the issue.

**Comment by Struggle-YD** [comment]
thank u very much!
